// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hoppzvWEqUt82Xs2DP7oZ7FZiaw4kRQ',
    appId: '1:694972334309:web:21972d8df3dd76fa67940c',
    messagingSenderId: '694972334309',
    projectId: 'syarta-portfolio',
    authDomain: 'syarta-portfolio.firebaseapp.com',
    storageBucket: 'syarta-portfolio.appspot.com',
    measurementId: 'G-62F5PJRHSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaxq6Pw8JZ87gsXEDgSBGtsO8FLm58g8E',
    appId: '1:694972334309:android:ed84fc7326612e0067940c',
    messagingSenderId: '694972334309',
    projectId: 'syarta-portfolio',
    storageBucket: 'syarta-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGP0s33JO6JPOgZXmcygfTUpUuK2SYxME',
    appId: '1:694972334309:ios:e0f49e15cc2f053c67940c',
    messagingSenderId: '694972334309',
    projectId: 'syarta-portfolio',
    storageBucket: 'syarta-portfolio.appspot.com',
    iosBundleId: 'syartaportfolio.com.syartaPortfolio',
  );
}
